// src/lib/biopage-constants.ts
import { SupportedLanguage } from '@/types/i18n';

export const DEFAULT_AVATAR =
  'https://upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png?20150327203541';

export const GRADIENT_PRESETS = [
  { label: 'Aurora', value: 'linear-gradient(135deg, #a855f7 0%, #22d3ee 50%, #0ea5e9 100%)' },
  { label: 'Sunset', value: 'linear-gradient(135deg, #ff6b6b 0%, #f8c146 50%, #f97316 100%)' },
  { label: 'Forest', value: 'linear-gradient(135deg, #22c55e 0%, #16a34a 50%, #0f766e 100%)' },
  { label: 'Midnight', value: 'linear-gradient(135deg, #0ea5e9 0%, #312e81 50%, #111827 100%)' },
  { label: 'Candy', value: 'linear-gradient(135deg, #ec4899 0%, #8b5cf6 50%, #6366f1 100%)' },
  { label: 'Tropical', value: 'linear-gradient(135deg, #fbbf24 0%, #f59e0b 35%, #10b981 100%)' },
  { label: 'Cosmic', value: 'linear-gradient(135deg, #4f46e5 0%, #9333ea 45%, #ec4899 100%)' },
  { label: 'Lagoon', value: 'linear-gradient(135deg, #06b6d4 0%, #0ea5e9 50%, #22c55e 100%)' },

  { label: 'Inferno', value: 'linear-gradient(135deg, #7f1d1d 0%, #dc2626 50%, #f97316 100%)' },
  { label: 'Ocean Deep', value: 'linear-gradient(135deg, #020617 0%, #0f172a 50%, #0369a1 100%)' },
  { label: 'Neon Night', value: 'linear-gradient(135deg, #22d3ee 0%, #818cf8 50%, #ec4899 100%)' },
  {
    label: 'Emerald Glow',
    value: 'linear-gradient(135deg, #064e3b 0%, #10b981 50%, #6ee7b7 100%)',
  },
  {
    label: 'Purple Storm',
    value: 'linear-gradient(135deg, #312e81 0%, #7c3aed 50%, #c084fc 100%)',
  },
  { label: 'Firefly', value: 'linear-gradient(135deg, #14532d 0%, #22c55e 50%, #fde047 100%)' },
  { label: 'Rose Gold', value: 'linear-gradient(135deg, #881337 0%, #ec4899 50%, #fbcfe8 100%)' },
  { label: 'Cyber Blue', value: 'linear-gradient(135deg, #020617 0%, #0ea5e9 50%, #38bdf8 100%)' },
  { label: 'Obsidian', value: 'linear-gradient(135deg, #020617 0%, #18181b 50%, #3f3f46 100%)' },
  { label: 'Peach Sky', value: 'linear-gradient(135deg, #fed7aa 0%, #fb923c 50%, #f97316 100%)' },
  { label: 'Mint Ice', value: 'linear-gradient(135deg, #99f6e4 0%, #2dd4bf 50%, #0f766e 100%)' },
  { label: 'Solar Flare', value: 'linear-gradient(135deg, #fde047 0%, #f59e0b 50%, #dc2626 100%)' },
  { label: 'Galaxy', value: 'linear-gradient(135deg, #020617 0%, #4f46e5 50%, #9333ea 100%)' },
  { label: 'Steel', value: 'linear-gradient(135deg, #334155 0%, #64748b 50%, #cbd5f5 100%)' },
  {
    label: 'Crimson Night',
    value: 'linear-gradient(135deg, #020617 0%, #7f1d1d 50%, #dc2626 100%)',
  },
  { label: 'Skyline', value: 'linear-gradient(135deg, #38bdf8 0%, #818cf8 50%, #e879f9 100%)' },
  { label: 'Sandstorm', value: 'linear-gradient(135deg, #fef3c7 0%, #fbbf24 50%, #92400e 100%)' },
  { label: 'Deep Teal', value: 'linear-gradient(135deg, #042f2e 0%, #0f766e 50%, #14b8a6 100%)' },
  {
    label: 'Electric Lime',
    value: 'linear-gradient(135deg, #4d7c0f 0%, #84cc16 50%, #d9f99d 100%)',
  },
  { label: 'Violet Dusk', value: 'linear-gradient(135deg, #2e1065 0%, #6d28d9 50%, #a78bfa 100%)' },
  { label: 'Iceberg', value: 'linear-gradient(135deg, #e0f2fe 0%, #38bdf8 50%, #0ea5e9 100%)' },
  { label: 'Blood Moon', value: 'linear-gradient(135deg, #020617 0%, #991b1b 50%, #ef4444 100%)' },
] as const;

export const BIOPAGE_TRANSLATIONS: Record<SupportedLanguage, { [key: string]: string }> = {
  en: {
    loading: 'Loading...',
    unauthorized: 'Unauthorized',
    noBiopage: 'No biopage yet',
    wantGenerate: 'Create your personalized biopage to share all your links in one place',
    generate: 'Create Biopage',
    changeUsername: 'Change your username',
    save: 'Save',
    usernamePlaceholder: 'Insert a new username',
    changeNote: 'You can change it every 3 days, choose wisely.',
    avatarQuestion: 'Change avatar',
    avatarSuccess: 'Avatar updated successfully',
    avatarError: 'Error!',
    close: 'Close',
    premiumBadge: 'Premium',
    freeBadge: 'Free',
    changeName: 'Change username',
    linksTitle: 'Visible links',
    linksDescription: 'Select which links appear on your biopage and customize their labels.',
    noLinks: 'No links available',
    displayName: 'Display name',
    background: 'Background',
    appearanceTitle: 'Style & appearance',
    appearanceDescription: 'Customize colors and gradients to match your brand.',
    textColor: 'Text color',
    gradients: 'Gradient themes',
    customColor: 'Custom color',
    colorHelp: 'Use hex colors or CSS values',
    avatarLabel: 'Avatar URL',
    saveBiopage: 'Save changes',
    viewBiopage: 'View biopage',
    preview: 'Live preview',
    created: 'Biopage created successfully',
    createError: 'Error creating biopage',
    saved: 'Saved successfully',
    saveError: 'Error saving biopage',
    updateError: 'There is no biopage to update',
    slugSaved: 'Username updated',
    slugErrorPrefix: 'Error:',
    avatarPrompt: 'Upload a new avatar',
    avatarUploadSuccess: 'Avatar updated successfully',
    profileTitle: 'Profile',
    profileDescription: 'Manage your public identity and avatar.',
    premiumHint: 'Premium users can customize their username',
    cancel: 'Cancel',
    selectLanguage: 'Language',
    descriptionLabel: 'Bio description',
    descriptionPlaceholder: 'Tell people who you are or what you do...',
    blur: 'Blur',
    backgroundImage: 'Select image to setup a background',
  },
  es: {
    loading: 'Cargando...',
    unauthorized: 'No autorizado',
    noBiopage: 'Aún no tienes biopage',
    wantGenerate: 'Crea tu biopage personalizada para compartir todos tus enlaces en un solo lugar',
    generate: 'Crear Biopage',
    changeUsername: 'Cambiar nombre de usuario',
    save: 'Guardar',
    usernamePlaceholder: 'Nuevo nombre de usuario',
    changeNote: 'Puedes cambiarlo cada 3 días, elige bien.',
    avatarQuestion: 'Cambiar avatar',
    avatarSuccess: 'Avatar actualizado',
    avatarError: '¡Error!',
    close: 'Cerrar',
    premiumBadge: 'Premium',
    freeBadge: 'Gratis',
    changeName: 'Cambiar usuario',
    linksTitle: 'Enlaces visibles',
    linksDescription: 'Selecciona qué enlaces aparecen en tu biopage y personaliza sus etiquetas.',
    noLinks: 'No hay enlaces',
    displayName: 'Nombre para mostrar',
    background: 'Fondo',
    appearanceTitle: 'Estilo y apariencia',
    appearanceDescription: 'Personaliza colores y degradados para tu marca.',
    textColor: 'Color de texto',
    gradients: 'Temas degradados',
    customColor: 'Color personalizado',
    colorHelp: 'Usa colores hex o valores CSS',
    avatarLabel: 'URL del avatar',
    saveBiopage: 'Guardar cambios',
    viewBiopage: 'Ver biopage',
    preview: 'Vista previa',
    created: 'Biopage creada exitosamente',
    createError: 'Error al crear biopage',
    saved: 'Guardado exitosamente',
    saveError: 'Error al guardar',
    updateError: 'No hay biopage para actualizar',
    slugSaved: 'Usuario actualizado',
    slugErrorPrefix: 'Error:',
    avatarPrompt: 'Sube un nuevo avatar',
    avatarUploadSuccess: 'Avatar actualizado',
    profileTitle: 'Perfil',
    profileDescription: 'Administra tu identidad pública y avatar.',
    premiumHint: 'Los usuarios Premium pueden personalizar su usuario',
    cancel: 'Cancelar',
    selectLanguage: 'Idioma',
    descriptionLabel: 'Descripción de bio',
    descriptionPlaceholder: 'Cuéntale a la gente quién eres o qué haces...',
    blur: 'Blur',
    backgroundImage: 'Selecciona una imagen de fondo',
  },
};
