export const COUNTRY_NAMES: Record<string, string> = {
    AF: 'Afganistán',
    AL: 'Albania',
    AO: 'Angola',
    AR: 'Argentina',
    AM: 'Armenia',
    AU: 'Australia',
    AT: 'Austria',
    AZ: 'Azerbaiyán',
    BD: 'Bangladés',
    BE: 'Bélgica',
    BF: 'Burkina Faso',
    BG: 'Bulgaria',
    BI: 'Burundi',
    BJ: 'Benín',
    BO: 'Bolivia',
    BR: 'Brasil',
    BW: 'Botsuana',
    BY: 'Bielorrusia',
    CA: 'Canadá',
    CD: 'República Democrática del Congo',
    CF: 'República Centroafricana',
    CH: 'Suiza',
    CL: 'Chile',
    CN: 'China',
    CO: 'Colombia',
    CR: 'Costa Rica',
    CU: 'Cuba',
    CZ: 'Chequia',
    DE: 'Alemania',
    DK: 'Dinamarca',
    DO: 'República Dominicana',
    DZ: 'Argelia',
    EC: 'Ecuador',
    EE: 'Estonia',
    EG: 'Egipto',
    ES: 'España',
    FI: 'Finlandia',
    FR: 'Francia',
    GB: 'Reino Unido',
    GE: 'Georgia',
    GH: 'Ghana',
    GL: 'Groenlandia',
    GN: 'Guinea',
    GQ: 'Guinea Ecuatorial',
    GR: 'Grecia',
    GT: 'Guatemala',
    HN: 'Honduras',
    HR: 'Croacia',
    HT: 'Haití',
    HU: 'Hungría',
    ID: 'Indonesia',
    IE: 'Irlanda',
    IL: 'Israel',
    IN: 'India',
    IQ: 'Irak',
    IR: 'Irán',
    IS: 'Islandia',
    IT: 'Italia',
    JM: 'Jamaica',
    JO: 'Jordania',
    JP: 'Japón',
    KE: 'Kenia',
    KG: 'Kirguistán',
    KH: 'Camboya',
    KP: 'Corea del Norte',
    KR: 'Corea del Sur',
    KW: 'Kuwait',
    KZ: 'Kazajistán',
    LA: 'Laos',
    LB: 'Líbano',
    LK: 'Sri Lanka',
    LR: 'Liberia',
    LS: 'Lesoto',
    LT: 'Lituania',
    LU: 'Luxemburgo',
    LV: 'Letonia',
    LY: 'Libia',
    MA: 'Marruecos',
    MD: 'Moldavia',
    ME: 'Montenegro',
    MG: 'Madagascar',
    MK: 'Macedonia del Norte',
    ML: 'Malí',
    MM: 'Myanmar',
    MN: 'Mongolia',
    MR: 'Mauritania',
    MT: 'Malta',
    MX: 'México',
    MY: 'Malasia',
    MZ: 'Mozambique',
    NA: 'Namibia',
    NE: 'Níger',
    NG: 'Nigeria',
    NI: 'Nicaragua',
    NL: 'Países Bajos',
    NO: 'Noruega',
    NP: 'Nepal',
    NZ: 'Nueva Zelanda',
    OM: 'Omán',
    PA: 'Panamá',
    PE: 'Perú',
    PG: 'Papúa Nueva Guinea',
    PH: 'Filipinas',
    PK: 'Pakistán',
    PL: 'Polonia',
    PT: 'Portugal',
    PY: 'Paraguay',
    QA: 'Catar',
    RO: 'Rumania',
    RS: 'Serbia',
    RU: 'Rusia',
    RW: 'Ruanda',
    SA: 'Arabia Saudita',
    SD: 'Sudán',
    SE: 'Suecia',
    SG: 'Singapur',
    SI: 'Eslovenia',
    SK: 'Eslovaquia',
    SL: 'Sierra Leona',
    SN: 'Senegal',
    SO: 'Somalia',
    SR: 'Surinam',
    SV: 'El Salvador',
    SY: 'Siria',
    SZ: 'Esuatini',
    TD: 'Chad',
    TG: 'Togo',
    TH: 'Tailandia',
    TJ: 'Tayikistán',
    TL: 'Timor Oriental',
    TN: 'Túnez',
    TR: 'Turquía',
    TT: 'Trinidad y Tobago',
    TW: 'Taiwán',
    TZ: 'Tanzania',
    UA: 'Ucrania',
    UG: 'Uganda',
    US: 'Estados Unidos',
    UY: 'Uruguay',
    UZ: 'Uzbekistán',
    VE: 'Venezuela',
    VN: 'Vietnam',
    YE: 'Yemen',
    ZA: 'Sudáfrica',
    ZM: 'Zambia',
    ZW: 'Zimbabue',
    UNKNOWN: 'Desconocido',
};
